# Generated by Django 2.0.7 on 2020-05-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200530_1528'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('chatroom',)},
        ),
    ]
