# Generated by Django 2.0.7 on 2020-05-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200530_1926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together=set(),
        ),
    ]
